PAGE_SIZE = 4096
INTEGER_BYTE_SIZE = 4
MAX_RECORD_PER_PAGE = PAGE_SIZE // INTEGER_BYTE_SIZE

MAX_PAGE_RANGE = 32
'''How many base pages are in a Page Range'''
MAX_TAIL_PAGES_BEFORE_MERGING = 64

INDIRECTION_COLUMN = 0
RID_COLUMN = 1
TIMESTAMP_COLUMN = 2
SCHEMA_ENCODING_COLUMN = 3
BASE_PAGE_ID_COLUMN = 4

NUM_HIDDEN_COLUMNS = 5

RECORD_DELETION_FLAG = -1

# Buffer Pool Constants
MAX_NUM_FRAME = 64
MERGE_FRAME_ALLOCATION = 8